import type { UiScreenPayload } from '../ui'

export const marketSearchResultsPayload: UiScreenPayload = {
  screen: 'market.search.results',
  screen_version: 'v2',
  role: 'buyer',
  widgets: [
    {
      widget_type: 'market.desktop_header',
      schema_version: 'v1',
      slot: 'screen.header',
      state: 'default',
      data: {
        city: 'Москва',
        query: 'iphone',
        user: 'Нурид',
        notifications: 4,
      },
      actions: [
        { id: 'header.city', type: 'dialog', label: 'Сменить город' },
        { id: 'header.search', type: 'submit', label: 'Искать' },
        { id: 'header.favorites', type: 'navigate', target: '/favorites' },
      ],
    },
    {
      widget_type: 'market.category_strip',
      schema_version: 'v1',
      slot: 'market.search.header',
      state: 'default',
      data: {
        active_id: 'all',
        items: [
          { id: 'all', label: 'Все категории' },
          { id: 'electronics', label: 'Электроника' },
          { id: 'auto', label: 'Авто' },
          { id: 'property', label: 'Недвижимость' },
          { id: 'services', label: 'Услуги' },
        ],
      },
      actions: [{ id: 'category.change', type: 'toggle' }],
    },
    {
      widget_type: 'market.search_panel',
      schema_version: 'v1',
      slot: 'market.search.header',
      state: 'default',
      data: {
        query: 'iphone',
        city: 'Москва',
        chips: ['Новые', 'С доставкой', 'Проверенные', 'С гарантией'],
      },
      actions: [{ id: 'search.submit', type: 'submit', label: 'Найти' }],
    },
    {
      widget_type: 'market.filter_bar',
      schema_version: 'v1',
      slot: 'market.search.filters',
      state: 'default',
      data: {
        filters: ['Категория', 'Цена', 'Состояние', 'Доставка'],
        chips: ['С доставкой', 'Проверенный продавец', 'Только избранное'],
        sort: 'new',
      },
      actions: [
        { id: 'filters.open', type: 'dialog', label: 'Открыть фильтры' },
        { id: 'filters.apply', type: 'submit', label: 'Применить' },
      ],
    },
    {
      widget_type: 'market.listing_card',
      schema_version: 'v1',
      slot: 'market.results.grid',
      state: 'default',
      data: {
        id: 'l-1001',
        title: 'iPhone 15 Pro 256GB',
        price: '89 000 ₽',
        meta: 'Москва · сегодня',
        status: 'Проверено',
        favorite: true,
        category: 'electronics',
        delivery: true,
      },
      actions: [
        { id: 'listing.open.l-1001', type: 'navigate', target: '/item/l-1001' },
        { id: 'favorite.toggle.l-1001', type: 'command' },
      ],
    },
    {
      widget_type: 'market.listing_card',
      schema_version: 'v1',
      slot: 'market.results.grid',
      state: 'default',
      data: {
        id: 'l-1002',
        title: 'MacBook Air M3 16/512',
        price: '137 000 ₽',
        meta: 'Москва · 2 часа назад',
        status: 'Есть доставка',
        favorite: false,
        category: 'electronics',
        delivery: true,
      },
      actions: [
        { id: 'listing.open.l-1002', type: 'navigate', target: '/item/l-1002' },
        { id: 'favorite.toggle.l-1002', type: 'command' },
      ],
    },
    {
      widget_type: 'market.listing_card',
      schema_version: 'v1',
      slot: 'market.results.grid',
      state: 'default',
      data: {
        id: 'l-1003',
        title: 'PlayStation 5 Slim + 2 геймпада',
        price: '49 000 ₽',
        meta: 'Мытищи · вчера',
        status: 'Проверено',
        favorite: false,
        category: 'electronics',
        delivery: false,
      },
      actions: [
        { id: 'listing.open.l-1003', type: 'navigate', target: '/item/l-1003' },
        { id: 'favorite.toggle.l-1003', type: 'command' },
      ],
    },
    {
      widget_type: 'market.listing_card',
      schema_version: 'v1',
      slot: 'market.results.grid',
      state: 'default',
      data: {
        id: 'l-2001',
        title: 'Li Auto L9 2024, полный привод',
        price: '4 890 000 ₽',
        meta: 'Аргун · сегодня',
        status: 'Проверено',
        favorite: true,
        category: 'auto',
        delivery: false,
      },
      actions: [
        { id: 'listing.open.l-2001', type: 'navigate', target: '/item/l-2001' },
        { id: 'favorite.toggle.l-2001', type: 'command' },
      ],
    },
    {
      widget_type: 'market.listing_card',
      schema_version: 'v1',
      slot: 'market.results.grid',
      state: 'default',
      data: {
        id: 'l-2002',
        title: 'Toyota Camry 3.5, 2022',
        price: '3 050 000 ₽',
        meta: 'Москва · сегодня',
        status: 'Есть доставка',
        favorite: false,
        category: 'auto',
        delivery: true,
      },
      actions: [
        { id: 'listing.open.l-2002', type: 'navigate', target: '/item/l-2002' },
        { id: 'favorite.toggle.l-2002', type: 'command' },
      ],
    },
    {
      widget_type: 'market.listing_card',
      schema_version: 'v1',
      slot: 'market.results.grid',
      state: 'default',
      data: {
        id: 'l-3001',
        title: 'Студия 32 м², 6/22 этаж',
        price: '65 000 ₽ / мес',
        meta: 'Москва · 40 минут назад',
        status: 'Проверено',
        favorite: false,
        category: 'property',
        delivery: false,
      },
      actions: [
        { id: 'listing.open.l-3001', type: 'navigate', target: '/item/l-3001' },
        { id: 'favorite.toggle.l-3001', type: 'command' },
      ],
    },
    {
      widget_type: 'market.listing_card',
      schema_version: 'v1',
      slot: 'market.results.grid',
      state: 'default',
      data: {
        id: 'l-4001',
        title: 'Репетитор IELTS / TOEFL онлайн',
        price: '2 200 ₽ / час',
        meta: 'Москва · сегодня',
        status: 'Проверено',
        favorite: false,
        category: 'services',
        delivery: false,
      },
      actions: [
        { id: 'listing.open.l-4001', type: 'navigate', target: '/item/l-4001' },
        { id: 'favorite.toggle.l-4001', type: 'command' },
      ],
    },
    {
      widget_type: 'market.desktop_widgets',
      schema_version: 'v1',
      slot: 'market.results.sidebar',
      state: 'default',
      data: {
        widgets: {
          highlights: [
            { id: 'new_today', title: 'Новых за сутки', value: '1 284', note: '+8% к вчера' },
            { id: 'trusted', title: 'Проверенных продавцов', value: '73%', note: 'в этой выдаче' },
            { id: 'delivery', title: 'С доставкой', value: '56%', note: 'в выбранной категории' },
          ],
          mini_rows: [
            { id: 'promo', title: 'Продвижение объявлений', price: 'от 89 ₽', meta: 'Охват +48%', status: 'success' },
            { id: 'recheck', title: 'Проверка объявлений', price: 'до 30 мин', meta: '2 задачи ждут решения', status: 'warning' },
            { id: 'drafts', title: 'Черновики', price: '14 шт', meta: 'Не опубликованы', status: 'muted' },
          ],
        },
      },
      actions: [{ id: 'widgets.open.promo', type: 'open_url', target: '/promotion' }],
    },
    {
      widget_type: 'core.navigation.pagination',
      schema_version: 'v1',
      slot: 'list.footer',
      state: 'default',
      data: {
        current_page: 1,
        total_pages: 3,
      },
      actions: [{ id: 'pagination.change', type: 'navigate' }],
    },
  ],
}

export const marketSearchResultsEmptyPayload: UiScreenPayload = {
  ...marketSearchResultsPayload,
  screen_version: 'v2-empty',
  widgets: [
    ...marketSearchResultsPayload.widgets.filter((widget) => widget.widget_type !== 'market.listing_card'),
    {
      widget_type: 'core.feedback.empty_state',
      schema_version: 'v1',
      slot: 'list.body',
      state: 'empty',
      data: {
        title: 'Ничего не найдено',
        description: 'Измените запрос или сбросьте фильтры, чтобы увидеть больше вариантов.',
        cta: 'Сбросить фильтры',
      },
      actions: [{ id: 'empty.reset_filters', type: 'command' }],
    },
  ],
}
